controller.player2.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    simplified.moveToRandomHoleOnGrid(myMole)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    simplified.moveToRandomHoleOnGrid(myMole)
    music.knock.play()
    animation.runImageAnimation(
    myHammer,
    [img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .....................44444444444
        .....................44444444444
        .....................22222222222
        .....................22222222222
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .cccccccccccccccccccceeeeeeeeeee
        .ddddddddddddddddddddeeeeeeeeeee
        .ddddddddddddddddddddeeeeeeeeeee
        .bbbbbbbbbbbbbbbbbbbbeeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................88888888888
        .....................88888888888
        .....................66666666666
        .....................66666666666
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .....................44444444444
        .....................44444444444
        .....................22222222222
        .....................22222222222
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .cccccccccccccccccccceeeeeeeeeee
        .ddddddddddddddddddddeeeeeeeeeee
        .dddddddddddddddddddbeeeeeeeeeee
        .bbbbbbbbbbbbbbbbbbbbeeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................88888888888
        .....................88888888888
        .....................66666666666
        .....................66666666666
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        ................................
        ...ddcc.........................
        ...ddcc.........................
        ...bbddcc.......................
        ...bbddcc.......................
        .....bbddcc.....................
        .....bbddcc.....................
        .......bbddcc...................
        .......bbddcc...................
        .........bbddcc........44.......
        .........bbddcc........44.......
        ...........bbddcc....ee2244.....
        ...........bbddcc....ee2244.....
        .............bbddcceeeeee2244...
        .............bbddcceeeeee2244...
        ...............bbddeeeeeeee2244.
        ...............bbddeeeeeeee2244.
        ...............eeeeeeeeeeeeee224
        ...............eeeeeeeeeeeeee224
        .............eeeeeeeeeeeeeeeeee.
        .............eeeeeeeeeeeeeeeeee.
        ...........6688eeeeeeeeeeeeee...
        ...........6688eeeeeeeeeeeeee...
        .............6688eeeeeeeeee.....
        .............6688eeeeeeeeee.....
        ...............6688eeeeee.......
        ...............6688eeeeee.......
        .................6688ee.........
        .................6688ee.........
        ...................66...........
        ...................66...........
        ................................
        `,img`
        ................................
        ...ddcc.........................
        ...ddcc.........................
        ...bbddcc.......................
        ...bbddcc.......................
        .....bbddcc.....................
        .....bbddcc.....................
        .......bbddcc...................
        .......bbddcc...................
        .........bbddcc........44.......
        .........bbddcc........44.......
        ...........bbddcc....ee2244.....
        ...........bbddcc....ee2244.....
        .............bbddcceeeeee2244...
        .............bbddcceeeeee2244...
        ...............bbddeeeeeeee2244.
        ...............bbddeeeeeeee2244.
        ...............eeeeeeeeeeeeee224
        ...............eeeeeeeeeeeeee224
        .............eeeeeeeeeeeeeeeeee.
        .............eeeeeeeeeeeeeeeeee.
        ...........6688eeeeeeeeeeeeee...
        ...........6688eeeeeeeeeeeeee...
        .............6688eeeeeeeeee.....
        .............6688eeeeeeeeee.....
        ...............6688eeeeee.......
        ...............6688eeeeee.......
        .................6688ee.........
        .................6688ee.........
        ...................66...........
        ...................66...........
        ................................
        `,img`
        ................................
        ...ddcc.........................
        ...ddcc.........................
        ...bbddcc.......................
        ...bbddcc.......................
        .....bbddcc.....................
        .....bbddcc.....................
        .......bbddcc...................
        .......bbddcc...................
        .........bbddcc........44.......
        .........bbddcc........44.......
        ...........bbddcc....ee2244.....
        ...........bbddcc....ee2244.....
        .............bbddcceeeeee2244...
        .............bbddcceeeeee2244...
        ...............bbddeeeeeeee2244.
        ...............bbddeeeeeeee2244.
        ...............eeeeeeeeeeeeee224
        ...............eeeeeeeeeeeeee224
        .............eeeeeeeeeeeeeeeeee.
        .............eeeeeeeeeeeeeeeeee.
        ...........6688eeeeeeeeeeeeee...
        ...........6688eeeeeeeeeeeeee...
        .............6688eeeeeeeeee.....
        .............6688eeeeeeeeee.....
        ...............6688eeeeee.......
        ...............6688eeeeee.......
        .................6688ee.........
        .................6688ee.........
        ...................66...........
        ...................66...........
        ................................
        `,img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        .....................44444444444
        .....................44444444444
        .....................22222222222
        .....................22222222222
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .cccccccccccccccccccceeeeeeeeeee
        .ddddddddddddddddddddeeeeeeeeeee
        .ddddddddddddddddddddeeeeeeeeeee
        .bbbbbbbbbbbbbbbbbbbbeeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................eeeeeeeeeee
        .....................88888888888
        .....................88888888888
        .....................66666666666
        .....................66666666666
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `,img`
        .................44.............
        ...............4422ee...........
        ...............4422ee...........
        .............4422eeeeee.........
        .............4422eeeeee.........
        ...........4422eeeeeeeeee.......
        ...........4422eeeeeeeeee.......
        .........4422eeeeeeeeeeeeee.....
        .........4422eeeeeeeeeeeeee.....
        ...........eeeeeeeeeeeeeeeeee...
        ...........eeeeeeeeeeeeeeeeee...
        .............eeeeeeeeeeeeee8866.
        .............eeeeeeeeeeeeee8866.
        .............ccddeeeeeeee8866...
        .............ccddeeeeeeee8866...
        ...........ccddbbeeeeee8866.....
        ...........ccddbbeeeeee8866.....
        .........ccddbb....ee8866.......
        .........ccddbb....ee8866.......
        .......ccddbb........66.........
        .......ccddbb........66.........
        .....ccddbb.....................
        .....ccddbb.....................
        ...ccddbb.......................
        ...ccddbb.......................
        .ccddbb.........................
        .ccddbb.........................
        .ddbb...........................
        .ddbb...........................
        ................................
        ................................
        ................................
        `],
    50,
    false
    )
})
let myMole: Sprite = null
let myHammer: Sprite = null
game.showLongText("Player 1: Use the arrow keys to move the hammer. Player 2: Press A to move the mole.", DialogLayout.Center)
scene.setBackgroundImage(assets.image`grid`)
myHammer = sprites.create(img`
    .................44.............
    ...............4422ee...........
    ...............4422ee...........
    .............4422eeeeee.........
    .............4422eeeeee.........
    ...........4422eeeeeeeeee.......
    ...........4422eeeeeeeeee.......
    .........4422eeeeeeeeeeeeee.....
    .........4422eeeeeeeeeeeeee.....
    ...........eeeeeeeeeeeeeeeeee...
    ...........eeeeeeeeeeeeeeeeee...
    .............eeeeeeeeeeeeee8866.
    .............eeeeeeeeeeeeee8866.
    .............ccddeeeeeeee8866...
    .............ccddeeeeeeee8866...
    ...........ccddbbeeeeee8866.....
    ...........ccddbbeeeeee8866.....
    .........ccddbb....ee8866.......
    .........ccddbb....ee8866.......
    .......ccddbb........66.........
    .......ccddbb........66.........
    .....ccddbb.....................
    .....ccddbb.....................
    ...ccddbb.......................
    ...ccddbb.......................
    .ccddbb.........................
    .ccddbb.........................
    .ddbb...........................
    .ddbb...........................
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
myMole = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . e e e e e e e e e e e e . . 
    . e e e e e e e e e e e e e e . 
    e e e e e e f e e f e e e e e e 
    e e e e e e f e e f e e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e f e e e e e e f e e e e 
    e e e e e f 3 3 3 3 f e e e e e 
    e e e e e e f 3 3 f e e e e e e 
    e e e e e f e e e e f e e e e e 
    e e e e e e e e e e e e e e e e 
    e e e f e e e e e e e e f e e e 
    e e e e f f f f f f f f e e e e 
    e e e e e e e e e e e e e e e e 
    e e e e e e e e e e e e e e e e 
    `, SpriteKind.Enemy)
simplified.moveOnlyOnscreenWithArrows(myHammer, simplified.Speeds.Fast)
carnival.addLabelTo("Whack-the-Mole", carnival.Areas.Bottom)
carnival.startCountdownGame(15, carnival.WinTypes.Score)
carnival.startCountdownGame(15, carnival.WinTypes.Multi)
game.onUpdateInterval(1000, function () {
    simplified.checkMoleEscape(mp.playerSelector(mp.PlayerNumber.Two), 1)
})
